# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1d6fa04d903d0e44e45a533eb97ff8fc849ad6bc2200dddc013e644aec23304f86491dfa51b173d6cde9412983986d80c097cfb45429a155c77dce8b7cdbe901

test:
  secret_key_base: b3e5cb4dfe61181e1022a9ea55bf235d688260dbe63f637ee9106127c256ea658f19b0b1d7100bb773f690ac17d85a654b0445b3ff8cfadb7a3934aacd766048

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
